import Image from "next/image";
import Link from "next/link";
import Icon, { type IconName } from "@/components/Icon";
import ContactForm from "@/components/ContactForm";
import { company, questions, services } from "@/lib/company";

const principles: { icon: IconName; title: string; description: string }[] = [
  { icon: "shield", title: "جودة في التنفيذ", description: "عناية بالتفاصيل في كل مرحلة" },
  { icon: "compass", title: "التزام في العمل", description: "وضوح ومسؤولية من البداية" },
  { icon: "spark", title: "رؤية للمستقبل", description: "حلول بناء أكثر استدامة" },
];
const sectors: { icon: IconName; title: string; detail: string }[] = [
  { icon: "home", title: "السكني", detail: "مبانٍ ومساحات للحياة" },
  { icon: "building", title: "الحكومي", detail: "منشآت تخدم المجتمع" },
  { icon: "store", title: "التجاري", detail: "وجهات للأعمال والتسوق" },
  { icon: "school", title: "التعليمي", detail: "بيئات للتعلّم والنمو" },
  { icon: "health", title: "الصحي", detail: "مرافق للرعاية الصحية" },
];

export default function Home() {
  return <main id="main-content">
    <section className="hero shell" aria-labelledby="hero-title">
      <div className="hero-panel">
        <div className="hero-copy">
          <div className="eyebrow"><span className="status-dot" />خطوط الإنشاء للمقاولات العامة</div>
          <h1 id="hero-title">نرسم خطوط <span className="highlight">المستقبل<span className="highlight-spark"><Icon name="spark" /></span></span><br />ونبنيها بإتقان.</h1>
          <p className="hero-description">من الفكرة إلى البناء. نجمع الخبرة الهندسية والالتزام بالجودة لنحوّل رؤيتك إلى واقع، ونترك أثرًا يدوم.</p>
          <div className="hero-actions"><a className="button button-blue" href="#contact">ابدأ مشروعك معنا <Icon name="arrow" /></a><a className="button button-quiet" href={company.profile} download><Icon name="download" />الملف التعريفي <span className="file-type">PDF</span></a></div>
          <div className="hero-principles">{principles.map(p => <div className="principle" key={p.title}><span className="principle-icon"><Icon name={p.icon} /></span><h2>{p.title}</h2><p>{p.description}</p></div>)}</div>
        </div>
        <div className="hero-visual"><Image src="/images/hero-construction.webp" fill sizes="(max-width: 760px) 90vw, 40vw" preload alt="مبانٍ قيد الإنشاء، من الملف التعريفي لخطوط الإنشاء" className="hero-photo" /><div className="photo-wash" /><span className="visual-label"><span />هندسة. التزام. أثر.</span><div className="visual-bottom"><span className="visual-circle"><Icon name="building" /></span><p>كل بناء عظيم<br /><strong>يبدأ بخط.</strong></p></div><span className="photo-source">من صور الملف التعريفي</span></div>
      </div>
      <div className="hero-caption"><span><Icon name="pin" />مكة المكرمة، المملكة العربية السعودية</span><a href="#about">اكتشف خطوط الإنشاء <span className="down-arrow">↓</span></a><span className="caption-english" lang="en">A VISION TAKES SHAPE.</span></div>
    </section>

    <section className="about-section shell section-space" id="about" aria-labelledby="about-title">
      <div className="about-copy"><span className="section-tag">01 — من نحن</span><h2 id="about-title">أكثر من أعمال بناء.<br /><span className="muted-heading">شراكة تقوم على الثقة.</span></h2><p>نحن شركة خطوط الإنشاء للمقاولات العامة، ننطلق من مكة المكرمة بخبرة هندسية وطموح للمساهمة في بناء مستقبل عمراني أفضل.</p><p>نجمع بين كفاءة المهندسين والفنيين، والاهتمام بالجودة والسلامة، لنقدّم حلولًا في أعمال المباني والبنية التحتية والإنشاءات المدنية، تتناسب مع احتياجات كل مشروع.</p><div className="about-vision"><span className="small-icon"><Icon name="compass" /></span><div><h3>رؤيتنا</h3><p>أن نكون شريكًا متميزًا في قطاع الإنشاءات، ندمج الخبرة والتقنيات الحديثة لبناء مستدام وفعّال.</p></div></div><a href={company.profile} download className="text-link">تعرّف علينا أكثر <Icon name="arrow" /></a></div>
      <div className="about-bento"><div className="about-image"><Image src="/images/about-construction.webp" fill sizes="(max-width: 760px) 90vw, 45vw" alt="فريق عمل في موقع إنشائي، من صور الملف التعريفي" /><div className="about-image-overlay"><span>رؤيتك في قلب عملنا</span><strong>نفكّر بدقة.<br />ونبني بثقة.</strong></div></div><div className="bento-card bento-navy"><Icon name="shield" /><h3>الجودة والسلامة</h3><p>مبدأ حاضر في طريقة عملنا.</p></div><div className="bento-card bento-blue"><span className="bento-number">03</span><div><h3>مجالات متكاملة</h3><p>لرؤية إنشائية أشمل.</p></div></div><span className="bento-orbit"><Icon name="spark" /></span></div>
    </section>

    <section className="services-section shell section-space" id="services" aria-labelledby="services-title"><div className="section-heading"><div><span className="section-tag">02 — ماذا نقدّم</span><h2 id="services-title">خبرات تتكامل.<br /><span className="muted-heading">لتكتمل رؤيتك.</span></h2></div><p>من المبنى إلى محيطه، نقدّم نطاقًا متنوعًا<br className="desktop-break" /> من الخدمات الإنشائية في ثلاثة مجالات رئيسية.</p></div><div className="services-grid">{services.map(s => <Link className="service-card" key={s.slug} href={`/services/${s.slug}/`}><div className="service-card-top"><span className="service-icon"><Icon name={s.icon} /></span><span className="service-number">{s.number}</span></div><h3>{s.title}</h3><p>{s.description}</p><div className="service-tags">{s.items.slice(0, 3).map(item => <span key={item}>{item}</span>)}</div><div className="service-link"><span>اكتشف الخدمة</span><span className="round-arrow"><Icon name="arrow" /></span></div></Link>)}</div></section>

    <section className="sectors-section shell section-space" id="sectors" aria-labelledby="sectors-title"><div className="section-heading compact"><div><span className="section-tag">03 — قطاعات نخدمها</span><h2 id="sectors-title">لكل قطاع، <span className="muted-heading">فهمٌ أعمق.</span></h2></div><p>نبني للناس، وللأعمال، وللمجتمع.</p></div><div className="sectors-grid">{sectors.map(s => <div className="sector" key={s.title}><Icon name={s.icon} /><h3>{s.title}</h3><p>{s.detail}</p></div>)}</div></section>

    <section className="process-section shell section-space" aria-labelledby="process-title"><div className="process-panel"><div className="process-intro"><span className="section-tag tag-light">04 — رحلتنا معك</span><h2 id="process-title">خطوات واضحة.<br />من أول حديث،<br /><span>إلى آخر تفصيلة.</span></h2><a href="#contact" className="button button-white">لنتحدث عن مشروعك <Icon name="arrow" /></a><div className="process-decoration" aria-hidden="true"><span /><span /><span /><span /></div></div><div className="process-steps">{[{ title: "نستمع ونفهم", text: "نبدأ برؤيتك، ونناقش متطلبات المشروع وموقعه وأهدافه." }, { title: "ندرس ونخطّط", text: "نراجع نطاق الأعمال والمخططات، ونحدّد المتطلبات الفنية." }, { title: "نتفق وننفّذ", text: "نوضّح نطاق العمل والجدول الزمني، ثم نتابع التنفيذ وفق المتفق عليه." }, { title: "نراجع ونسلّم", text: "نراجع الأعمال والتفاصيل وصولًا إلى التسليم حسب متطلبات المشروع." }].map((s, i) => <div className="process-step" key={s.title}><span className="step-number">0{i + 1}</span><div><h3>{s.title}</h3><p>{s.text}</p></div><Icon name="arrow" /></div>)}</div></div></section>

    <section className="quality-section shell section-space" id="quality" aria-labelledby="quality-title"><div className="section-heading"><div><span className="section-tag">05 — ما نبني عليه</span><h2 id="quality-title">قيم واضحة.<br /><span className="muted-heading">وأثر في كل تفصيلة.</span></h2></div><p>قوة البناء تبدأ من مبادئ راسخة،<br className="desktop-break" /> نضعها في صميم علاقتنا بعملائنا.</p></div><div className="values-grid">{[{ icon: "spark", title: "التميّز", text: "العناية بالمواصفات والتفاصيل، والسعي المستمر لتحسين جودة العمل." }, { icon: "compass", title: "الالتزام", text: "وضوح في الاتفاق، وتواصل مسؤول طوال مراحل المشروع." }, { icon: "building", title: "الابتكار", text: "توظيف الخبرة والتقنيات الحديثة لتقديم حلول إنشائية فعّالة." }, { icon: "shield", title: "المسؤولية", text: "الاهتمام بالسلامة والبيئة، واحترام الأثر الذي نتركه من حولنا." }].map(v => <div className="value-card" key={v.title}><Icon name={v.icon as IconName} /><h3>{v.title}</h3><p>{v.text}</p></div>)}</div><div className="credentials-strip"><div className="credentials-title"><span className="small-icon"><Icon name="file" /></span><div><h3>شريك تعرفه بوضوح</h3><p>شركة خطوط الإنشاء للمقاولات العامة</p></div></div><div><span>السجل التجاري</span><strong dir="ltr">{company.commercialRegistration}</strong></div><a href="#contact" className="text-link">اطلب وثائق التأهيل المحدثة <Icon name="arrow" /></a></div></section>

    <section className="profile-section shell section-space"><div className="profile-banner"><div className="profile-art" aria-hidden="true"><Icon name="file" /><span>KHOTOUT<br />COMPANY PROFILE</span><span className="profile-art-line" /></div><div><span className="section-tag">خطوط الإنشاء، عن قرب</span><h2>تعرّف على شريك<br />مشروعك القادم.</h2><p>رؤيتنا، قيمنا، ومجالات عملنا في ملف واحد.</p></div><a className="button button-navy" href={company.profile} download>حمّل الملف التعريفي <Icon name="download" /><span className="file-type">PDF</span></a></div></section>

    <section className="faq-section shell section-space" aria-labelledby="faq-title"><div><span className="section-tag">06 — أسئلة شائعة</span><h2 id="faq-title">قبل أن نبدأ،<br /><span className="muted-heading">قد تتساءل.</span></h2><p>إجابات تساعدك على أخذ الخطوة الأولى.</p><a href="#contact" className="text-link">لديك سؤال آخر؟ تواصل معنا <Icon name="arrow" /></a></div><div className="faq-list">{questions.map((q, i) => <details key={q.question} name="faq"><summary><span className="faq-number">0{i + 1}</span><h3>{q.question}</h3><Icon name="plus" /></summary><p>{q.answer}</p></details>)}</div></section>

    <section className="contact-section shell section-space" id="contact" aria-labelledby="contact-title"><div className="contact-panel"><div className="contact-copy"><span className="section-tag">07 — لنبنِ شيئًا معًا</span><h2 id="contact-title">مشروعك القادم،<br /><span className="blue-text">يبدأ بمحادثة.</span></h2><p>شاركنا فكرتك ومتطلباتك، ودعنا نناقش كيف نحولها إلى خطوات واضحة.</p><div className="contact-links"><a href={`tel:${company.phone}`}><span className="small-icon"><Icon name="phone" /></span><span><small>اتصل بنا مباشرة</small><strong dir="ltr">{company.phoneDisplay}</strong></span><Icon name="arrow" /></a><a href={company.maps} target="_blank" rel="noopener noreferrer"><span className="small-icon"><Icon name="pin" /></span><span><small>تجدنا في مكة المكرمة</small><strong>حي الملك فهد، أم الكتاد</strong><span className="address-code">العنوان المختصر: <bdi>{company.shortAddress}</bdi></span></span><Icon name="arrow" /></a></div><div className="contact-footnote"><span className="status-dot" />نسعد بمناقشة مشاريعكم واحتياجاتكم.</div></div><div className="contact-form-panel"><h3>أخبرنا عن مشروعك</h3><p>بعض التفاصيل لنبدأ الحديث من المكان الصحيح.</p><ContactForm /></div></div></section>
  </main>;
}
